name: CD to Docker Hub

on:
  create:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out Repo
      uses: actions/checkout@v2
  
    - name: Login to Docker Hub
      uses: docker/docker/login-action@v1
      with:
       username: ${{secrets.DOCKER_HUB_USERNAME}}
       password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/docker/setup-buildx-action@1
  
    - name: Build and push
      id: docker_build
      uses: docker/docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
  
